### PR TITLE
adding openBeta to repositories

### PR DESCRIPTION
**Pull request by vcbenj**
#### ℹ️ Repository information

**The repository has**:

- [x] At least three issues with the `good first issue` label.
- [x] At least 10 contributors.
- [x] Detailed setup instructions for the project.
- [x] CONTRIBUTING.md
- [x] Actively maintained.

### CODE REVIEW

**Review by simran-2501 — APPROVED** [review]

**Review by simran-2501 — APPROVED** [review]

**Comment by zichongkao** [comment]
@simran-2501 Checking in here again! We'd love to be added to the set of repos!

**Comment by vnugent** [comment]
@simran-2501 can you please merge?

**Comment by simran-2501** [comment]
Lemme check it once and then I'll merge

**Comment by simran-2501** [comment]
Oh okay...

**Review by sanket-deepsource — APPROVED** [review]

**Pull request merged**
