### PR TITLE
Added kiwix-android project

### PR DESCRIPTION
**Pull request by sourabhkumar47**
Issue link - https://github.com/kiwix/kiwix-android/issues

#### ℹ️ Repository information

**The repository has**:

- [x] At least three issues with the `good first issue` label.
- [x] At least 10 contributors.
- [x] Detailed setup instructions for the project.
- [x] CONTRIBUTING.md
- [x] Actively maintained.

### CODE REVIEW

**Comment by lucavallin** [comment]
Hey @sourabhkumar47  ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Comment by sourabhkumar47** [comment]
Thank you, @lucavallin, for connecting with me. I created a PR two months ago, but haven't heard back.
I'm glad you're keeping the project alive. I will certainly raise the PR to your forked project. While I'm interested in your mission to convert apps from Nuxt.js & Python to Next.js & Typescript, I am unfamiliar with Next.js and Typescript. However, I am familiar with Python.
Please let me know how I can contribute to your project.

**Comment by lucavallin** [comment]
@sourabhkumar47 Thank you! Since you know Python, I think it'd be nice to convert `data/repositories.toml` to `data/repositories.json` and support reading from json instead of toml here https://github.com/lucavallin/gfi/blob/main/generate.py  (while we work on converting it to Typescript). It'd be nice to lose the toml dependency.

**Review by withshubh — APPROVED** [review]
Thanks for adding Kiwix-android @sourabhkumar47 🙌

**Pull request closed without merging**
